features_names = ['age_group',
                'type_of_admission',
                'ccs_diagnosis_description',
                'ccs_procedure_description',
                'apr_drg_description',
                'apr_mdc_description',
                'apr_severity_of_illness_description',
                'apr_risk_of_mortality',
                'gender_M',
                'apr_medical_surgical_description_Surgical',
                'emergency_department_indicator_Y']


dict_age_group = {'18 to 29': 1, '30 to 49': 2, '50 to 69': 3, '70 or Older': 4}

dict_ccs_diagnosis_description = {'Abdominal hernia': 6.96,
                                'Abdominal pain': 4.37,
                                'Acquired foot deformities': 3.98,
                                'Acute and chronic tonsillitis': 2.84,
                                'Acute and unspecified renal failure': 10.25,
                                'Acute bronchitis': 4.2,
                                'Acute cerebrovascular disease': 10.87,
                                'Acute myocardial infarction': 8.69,
                                'Acute posthemorrhagic anemia': 5.78,
                                'Adjustment disorders': 7.06,
                                'Administrative/social admission': 12.98,
                                'Alcohol-related disorders': 8.67,
                                'Allergic reactions': 4.18,
                                'Anal and rectal conditions': 5.52,
                                'Anxiety disorders': 7.3,
                                'Aortic and peripheral arterial embolism or thrombosis': 8.55,
                                'Aortic; peripheral; and visceral artery aneurysms': 8.66,
                                'Appendicitis and other appendiceal conditions': 6.04,
                                'Aspiration pneumonitis; food/vomitus': 10.24,
                                'Asthma': 6.22,
                                'Attention-deficit, conduct, and disruptive behavior disorders': 7.99,
                                'Bacterial infection; unspecified site': 8.37,
                                'Benign neoplasm of uterus': 4.46,
                                'Biliary tract disease': 6.77,
                                'Birth trauma': 2.0,
                                'Blindness and vision defects': 3.28,
                                'Burns': 10.73,
                                'Calculus of urinary tract': 4.18,
                                'Cancer of bladder': 9.32,
                                'Cancer of bone and connective tissue': 8.44,
                                'Cancer of brain and nervous system': 9.94,
                                'Cancer of breast': 7.46,
                                'Cancer of bronchus; lung': 10.02,
                                'Cancer of cervix': 7.39,
                                'Cancer of colon': 11.11,
                                'Cancer of esophagus': 10.97,
                                'Cancer of head and neck': 11.38,
                                'Cancer of kidney and renal pelvis': 7.28,
                                'Cancer of liver and intrahepatic bile duct': 7.96,
                                'Cancer of other GI organs; peritoneum': 10.12,
                                'Cancer of other female genital organs': 6.86,
                                'Cancer of other male genital organs': 7.62,
                                'Cancer of other urinary organs': 6.61,
                                'Cancer of ovary': 8.91,
                                'Cancer of pancreas': 9.52,
                                'Cancer of prostate': 9.29,
                                'Cancer of rectum and anus': 10.49,
                                'Cancer of stomach': 10.68,
                                'Cancer of testis': 8.92,
                                'Cancer of thyroid': 5.27,
                                'Cancer of uterus': 8.49,
                                'Cancer; other and unspecified primary': 8.22,
                                'Cancer; other respiratory and intrathoracic': 8.03,
                                'Cardiac and circulatory congenital anomalies': 5.55,
                                'Cardiac arrest and ventricular fibrillation': 8.76,
                                'Cardiac dysrhythmias': 6.2,
                                'Cataract': 6.1,
                                'Chronic kidney disease': 8.14,
                                'Chronic obstructive pulmonary disease and bronchiectasis': 7.82,
                                'Chronic ulcer of skin': 11.01,
                                'Coagulation and hemorrhagic disorders': 6.28,
                                'Coma; stupor; and brain damage': 9.01,
                                'Complication of device; implant or graft': 8.8,
                                'Complications of surgical procedures or medical care': 7.47,
                                'Conditions associated with dizziness or vertigo': 3.76,
                                'Conduction disorders': 4.89,
                                'Congestive heart failure; nonhypertensive': 10.26,
                                'Contraceptive and procreative management': 2.7,
                                'Coronary atherosclerosis and other heart disease': 7.03,
                                'Crushing injury or internal injury': 8.28,
                                'Cystic fibrosis': 10.02,
                                'Deficiency and other anemia': 6.65,
                                'Delirium, dementia, and amnestic and other cognitive disorders': 14.95,
                                'Developmental disorders': 8.57,
                                'Diabetes mellitus with complications': 8.55,
                                'Diabetes mellitus without complication': 4.44,
                                'Diabetes or abnormal glucose tolerance complicating pregnancy; childbirth; or the puerperium': 3.65,
                                'Digestive congenital anomalies': 5.95,
                                'Diseases of mouth; excluding dental': 4.64,
                                'Diseases of white blood cells': 7.15,
                                'Disorders of lipid metabolism': 4.67,
                                'Disorders of teeth and jaw': 4.01,
                                'Disorders usually diagnosed in infancy, childhood, or adolescence': 15.53,
                                'Diverticulosis and diverticulitis': 7.76,
                                'E Codes: Unclassified': 4.67,
                                'Early or threatened labor': 5.26,
                                'Ectopic pregnancy': 2.59,
                                'Encephalitis (except that caused by tuberculosis or sexually transmitted disease)': 13.8,
                                'Endometriosis': 3.42,
                                'Epilepsy; convulsions': 6.89,
                                'Esophageal disorders': 5.42,
                                'Essential hypertension': 4.02,
                                'Female infertility': 2.57,
                                'Fetal distress and abnormal forces of labor': 3.21,
                                'Fetopelvic disproportion; obstruction': 3.09,
                                'Fever of unknown origin': 4.82,
                                'Fluid and electrolyte disorders': 6.48,
                                'Forceps delivery': 2.55,
                                'Fracture of lower limb': 8.67,
                                'Fracture of neck of femur (hip)': 9.66,
                                'Fracture of upper limb': 5.79,
                                'Gangrene': 12.03,
                                'Gastritis and duodenitis': 4.99,
                                'Gastroduodenal ulcer (except hemorrhage)': 7.67,
                                'Gastrointestinal hemorrhage': 6.87,
                                'Genitourinary congenital anomalies': 4.47,
                                'Genitourinary symptoms and ill-defined conditions': 5.06,
                                'Glaucoma': 4.03,
                                'Gout and other crystal arthropathies': 5.13,
                                'HIV infection': 11.26,
                                'Headache; including migraine': 3.83,
                                'Heart valve disorders': 10.83,
                                'Hemorrhage during pregnancy; abruptio placenta; placenta previa': 6.49,
                                'Hemorrhoids': 4.55,
                                'Hepatitis': 7.96,
                                'Hodgkin`s disease': 13.86,
                                'Hyperplasia of prostate': 5.72,
                                'Hypertension complicating pregnancy; childbirth and the puerperium': 5.43,
                                'Hypertension with complications and secondary hypertension': 7.88,
                                'Immunity disorders': 9.03,
                                'Immunizations and screening for infectious disease': 5.61,
                                'Impulse control disorders, NEC': 12.1,
                                'Induced abortion': 3.17,
                                'Infective arthritis and osteomyelitis (except that caused by tuberculosis or sexually transmitted disease)': 10.28,
                                'Inflammation; infection of eye (except that caused by tuberculosis or sexually transmitteddisease)': 4.97,
                                'Inflammatory conditions of male genital organs': 5.76,
                                'Inflammatory diseases of female pelvic organs': 4.82,
                                'Influenza': 6.66,
                                'Intestinal infection': 6.55,
                                'Intestinal obstruction without hernia': 9.08,
                                'Intracranial injury': 9.43,
                                'Joint disorders and dislocations; trauma-related': 4.01,
                                'Late effects of cerebrovascular disease': 13.18,
                                'Leukemias': 20.4,
                                'Lung disease due to external agents': 6.43,
                                'Lymphadenitis': 3.8,
                                'Maintenance chemotherapy; radiotherapy': 10.49,
                                'Malaise and fatigue': 6.78,
                                'Malignant neoplasm without specification of site': 8.13,
                                'Malposition; malpresentation': 3.86,
                                'Medical examination/evaluation': 2.08,
                                'Melanomas of skin': 7.23,
                                'Meningitis (except that caused by tuberculosis or sexually transmitted disease)': 8.17,
                                'Menopausal disorders': 3.85,
                                'Menstrual disorders': 2.91,
                                'Miscellaneous disorders': 7.18,
                                'Mood disorders': 16.72,
                                'Multiple myeloma': 14.31,
                                'Multiple sclerosis': 7.01,
                                'Mycoses': 10.21,
                                'Nausea and vomiting': 4.29,
                                'Neoplasms of unspecified nature or uncertain behavior': 7.0,
                                'Nephritis; nephrosis; renal sclerosis': 7.11,
                                'Nervous system congenital anomalies': 6.17,
                                'Non-Hodgkin`s lymphoma': 13.36,
                                'Noninfectious gastroenteritis': 4.99,
                                'Nonmalignant breast conditions': 3.96,
                                'Nonspecific chest pain': 3.51,
                                'Nutritional deficiencies': 9.49,
                                'OB-related trauma to perineum and vulva': 2.79,
                                'Occlusion or stenosis of precerebral arteries': 4.91,
                                'Open wounds of extremities': 5.31,
                                'Open wounds of head; neck; and trunk': 3.81,
                                'Osteoarthritis': 5.86,
                                'Osteoporosis': 6.58,
                                'Other CNS infection and poliomyelitis': 14.0,
                                'Other acquired deformities': 5.83,
                                'Other aftercare': 11.27,
                                'Other and ill-defined cerebrovascular disease': 6.02,
                                'Other and ill-defined heart disease': 5.22,
                                'Other and unspecified benign neoplasm': 5.74,
                                'Other bone disease and musculoskeletal deformities': 4.68,
                                'Other circulatory disease': 5.66,
                                'Other complications of birth; puerperium affecting management of mother': 4.9,
                                'Other complications of pregnancy': 4.52,
                                'Other congenital anomalies': 4.22,
                                'Other connective tissue disease': 6.17,
                                'Other diseases of bladder and urethra': 5.86,
                                'Other diseases of kidney and ureters': 4.71,
                                'Other diseases of veins and lymphatics': 7.02,
                                'Other disorders of stomach and duodenum': 6.7,
                                'Other ear and sense organ disorders': 4.01,
                                'Other endocrine disorders': 6.91,
                                'Other eye disorders': 3.72,
                                'Other female genital disorders': 4.56,
                                'Other fractures': 7.44,
                                'Other gastrointestinal disorders': 7.19,
                                'Other hematologic conditions': 6.33,
                                'Other hereditary and degenerative nervous system conditions': 7.65,
                                'Other infections; including parasitic': 6.12,
                                'Other inflammatory condition of skin': 7.13,
                                'Other injuries and conditions due to external causes': 5.59,
                                'Other liver diseases': 8.1,
                                'Other lower respiratory disease': 5.98,
                                'Other male genital disorders': 5.48,
                                'Other nervous system disorders': 7.33,
                                'Other non-epithelial cancer of skin': 7.49,
                                'Other non-traumatic joint disorders': 4.38,
                                'Other nutritional; endocrine; and metabolic disorders': 7.05,
                                'Other pregnancy and delivery including normal': 3.37,
                                'Other screening for suspected conditions (not mental disorders or infectious disease)': 3.83,
                                'Other skin disorders': 4.91,
                                'Other upper respiratory disease': 4.56,
                                'Other upper respiratory infections': 3.81,
                                'Otitis media and related conditions': 3.85,
                                'Ovarian cyst': 3.13,
                                'Pancreatic disorders (not diabetes)': 7.73,
                                'Paralysis': 9.69,
                                'Parkinson`s disease': 7.32,
                                'Pathological fracture': 8.8,
                                'Peri-; endo-; and myocarditis; cardiomyopathy (except that caused by tuberculosis or sexually transmitted disease)': 7.95,
                                'Peripheral and visceral atherosclerosis': 7.62,
                                'Peritonitis and intestinal abscess': 8.59,
                                'Personality disorders': 9.47,
                                'Phlebitis; thrombophlebitis and thromboembolism': 7.02,
                                'Pleurisy; pneumothorax; pulmonary collapse': 8.37,
                                'Pneumonia (except that caused by tuberculosis or sexually transmitted disease)': 8.69,
                                'Poisoning by nonmedicinal substances': 5.48,
                                'Poisoning by other medications and drugs': 5.46,
                                'Poisoning by psychotropic agents': 4.97,
                                'Polyhydramnios and other problems of amniotic cavity': 6.24,
                                'Postabortion complications': 3.02,
                                'Previous C-section': 3.76,
                                'Prolapse of female genital organs': 2.88,
                                'Prolonged pregnancy': 3.19,
                                'Pulmonary heart disease': 7.51,
                                'Regional enteritis and ulcerative colitis': 7.49,
                                'Rehabilitation care; fitting of prostheses; and adjustment of devices': 17.11,
                                'Residual codes; unclassified': 5.83,
                                'Respiratory failure; insufficiency; arrest (adult)': 14.09,
                                'Retinal detachments; defects; vascular occlusion; and retinopathy': 3.1,
                                'Rheumatoid arthritis and related disease': 5.58,
                                'Schizophrenia and other psychotic disorders': 26.07,
                                'Screening and history of mental health and substance abuse codes': 7.82,
                                'Secondary malignancies': 8.75,
                                'Septicemia (except in labor)': 14.06,
                                'Sexually transmitted infections (not HIV or hepatitis)': 7.22,
                                'Shock': 11.06,
                                'Sickle cell anemia': 9.29,
                                'Skin and subcutaneous tissue infections': 7.23,
                                'Skull and face fractures': 5.02,
                                'Spinal cord injury': 14.06,
                                'Spondylosis; intervertebral disc disorders; other back problems': 6.55,
                                'Spontaneous abortion': 2.36,
                                'Sprains and strains': 4.27,
                                'Substance-related disorders': 8.61,
                                'Suicide and intentional self-inflicted injury': 5.47,
                                'Superficial injury; contusion': 4.74,
                                'Syncope': 4.61,
                                'Systemic lupus erythematosus and connective tissue disorders': 7.92,
                                'Thyroid disorders': 5.73,
                                'Transient cerebral ischemia': 4.18,
                                'Tuberculosis': 22.62,
                                'Umbilical cord complication': 3.61,
                                'Urinary tract infections': 7.68,
                                'Varicose veins of lower extremity': 6.04,
                                'Viral infection': 5.44}

dict_ccs_procedure_description = {'ABDOMINAL PARACENTESIS': 9.04,
                                'ABORTION (TERM OF PREG)': 6.46,
                                'ALCO/DRUG REHAB/DETOX': 9.62,
                                'AMPUTATE LOWER EXTRMITY': 14.49,
                                'AORTIC RESECTION; REPL': 9.72,
                                'APPENDECTOMY': 6.6,
                                'ART RUPT MEMB ASSIS DLV': 2.67,
                                'ARTERIAL BLOOD GASES': 4.85,
                                'ARTERIO FEMORAL/LOW ART': 6.99,
                                'ARTERIO/VENOGRAM-NOT HH': 5.84,
                                'ARTERIOVENOUS FISTULA': 14.18,
                                'ARTHROCENTESIS': 7.62,
                                'ARTHROPLASTY KNEE': 6.68,
                                'ARTHROPLASTY-NOT HIP/KN': 3.8,
                                'ARTHROSCOPY': 5.22,
                                'BIOPSY OF LIVER': 9.21,
                                'BLOOD TRANSFUSION': 7.83,
                                'BONE MARROW BIOPSY': 17.08,
                                'BONE MARROW TRANSPLANT': 28.38,
                                'BREAST BIOPSY & DX PRCS': 8.82,
                                'BUNIONECTOMY/TOE DEFORM': 4.81,
                                'CANCER CHEMOTHERAPY': 11.96,
                                'CARDIAC PACEMAKER/DEFIB': 7.72,
                                'CARDIAC STRESS TESTS': 3.99,
                                'CEREBRAL ARTERIOGRAM': 6.24,
                                'CESAREAN SECTION': 8.25,
                                'CHOLECYSTECTOMY/EXPLOR': 7.99,
                                'CIRCUMCISION': 11.54,
                                'COLONOSCOPY AND BIOPSY': 7.61,
                                'COLORECTAL RESECTION': 12.72,
                                'COLOSTOMY; TEMP/PERM': 13.83,
                                'COMP AXIAL TOMOGR (CT)': 5.48,
                                'CONTRAST AORTOGRAM': 7.68,
                                'CONTROL OF EPISTAXIS': 6.07,
                                'CONV OF CARDIAC RHYTHM': 6.37,
                                'COR ARTERY BYP GRF-CABG': 13.14,
                                'CORNEAL TRANSPLANT': 6.55,
                                'CORONARY THROMBOLYSIS': 5.5,
                                'CT SCAN ABDOMEN': 4.5,
                                'CT SCAN CHEST': 4.89,
                                'D&C; ASPIR AFT DLV/ABOR': 3.04,
                                'DEBRIDE WOUND,INF,BURN': 10.71,
                                'DECOMP PERIPHERAL NERVE': 4.67,
                                'DES LES RETINA/CHOROID': 4.27,
                                'DIAGNOSTIC SPINAL TAP': 8.38,
                                'DIV OF JOINT CAPSULE': 3.72,
                                'DX AMNIOCENTESIS': 3.67,
                                'DX BRONCHOSCOPY & BIOPS': 10.11,
                                'DX CARDIAC CATHETERIZTN': 6.65,
                                'DX DILAT/CURETTAGE -D&C': 5.36,
                                'DX ENDOCRINE PRCS': 8.94,
                                'DX PHYSICAL THERAPY': 10.84,
                                'DX PRCS ON EAR': 7.77,
                                'DX PRCS ON EYE': 6.05,
                                'DX PRCS ON NOSE & MOUTH': 7.11,
                                'DX PRCS; MALE GENITAL': 10.11,
                                'DX ULTRASOUND AB/RETRO': 4.28,
                                'DX ULTRASOUND HEAD/NECK': 4.57,
                                'DX ULTRASOUND HEART': 6.08,
                                'DX ULTRASOUND OF GI': 5.31,
                                'DX ULTRASOUND URINARY': 5.25,
                                'ELECTROCARDIOGRAM': 4.13,
                                'ELECTROENCEPHALOGRAM': 6.58,
                                'ELECTROGR CARDIAC MONIT': 4.3,
                                'EMBOL-/ENDARTER-ECTOMY': 8.22,
                                'ENDARTERECTOMY;VES HEAD': 7.33,
                                'ENDO RETRO CAN OF PANCR': 7.13,
                                'ENDOSCOPY URINARY TRACT': 7.61,
                                'ENTERAL/PARENTERAL NUTR': 11.39,
                                'EPISIOTOMY': 2.93,
                                'ESOPHAGEAL DILATATION': 6.7,
                                'EXC OF SEMI CART KNEE': 6.3,
                                'EXCISION OF SKIN LESION': 8.02,
                                'EXCISION; LYS PERI ADHS': 10.54,
                                'EXPLORATORY LAPAROTOMY': 10.25,
                                'EXTRA CIRC AUX OPEN HRT': 20.9,
                                'EXTRACORP LTIHO;URINARY': 5.12,
                                'FETAL MONITORING': 4.39,
                                'FORCEP;VAC;BREACH DELIV': 2.93,
                                'GASTRECTOMY; PART/TOTAL': 9.44,
                                'GASTROSTOMY; TEMP/PERM': 15.2,
                                'GENI INCONTINENCE PRCS': 1.7,
                                'GLAUCOMA PROCEDURES': 5.03,
                                'HEART VALVE PRCS': 13.84,
                                'HEMODIALYSIS': 7.69,
                                'HEMORRHOID PRCS': 6.16,
                                'HIP REPLACEMENT,TOT/PRT': 8.42,
                                'HYSTERECTOMY; AB/VAG': 5.37,
                                'ILEO- & OT ENTER-OSTOMY': 15.05,
                                'INCIS/DRAIN, SKIN/SUBCU': 7.43,
                                'INCISION & EXCISION CNS': 11.81,
                                'INCISION OF PLEURA': 9.97,
                                'INDWELLING CATHETER': 6.87,
                                'INGUINAL/FEMORAL HERNIA': 6.82,
                                'INJ/ASP MUSC,TENDONS,ST': 8.18,
                                'INJ/LIG ESOPH VARICES': 4.71,
                                'INS CATHETER/SPNL STIM': 6.67,
                                'INTRAOP CHOLANGIOGRAM': 7.71,
                                'INTRAVENOUS PYELOGRAM': 4.56,
                                'IRR XCRANIAL VENT SHUNT': 11.18,
                                'KIDNEY TRANSPLANT': 8.17,
                                'LAMINECTOMY; EXC IV DSC': 7.06,
                                'LAPAROSCOPY': 6.16,
                                'LENS & CATARACT PRCS': 7.19,
                                'LIG/OCCL FALLOPIAN TUBE': 2.7,
                                'LOBECTOMY/PNEUMONECTOMY': 8.35,
                                'LOC EXC LRG INTEST LESN': 10.44,
                                'LOWER GI X-RAY': 5.45,
                                'LUMPECTOMY, QUAD BREAST': 4.81,
                                'MAG RESONANCE IMAGING': 5.73,
                                'MAMMOGRAPHY': 17.56,
                                'MASTECTOMY': 4.08,
                                'MASTOIDECTOMY': 6.25,
                                'MICRO EX (BACT SMEAR)': 7.19,
                                'MYELOGRAM': 6.89,
                                'MYRINGOTOMY': 10.02,
                                'NASOGASTRIC TUBE': 6.96,
                                'NEPHRECTOMY; PART/TOTAL': 6.64,
                                'NEPHRO-/NEPHROS-TOMY': 8.79,
                                'NO PROC': 7.57,
                                'NONOP RMVL FOREIGN BODY': 6.22,
                                'NONOP URINARY SYS MEASR': 5.62,
                                'OOPHORECTOMY; UNI/BILAT': 5.42,
                                'OPEN PROSTATECTOMY': 5.77,
                                'OPHTHALM-/OT-OLOGIC DX': 4.86,
                                'ORAL AND DENTAL SVCS': 8.63,
                                'OT DX CARDIOVASC PRCS': 6.96,
                                'OT DX PRC (INTERVW,EVAL': 5.89,
                                'OT DX PRC SKIN/SUBCUTAN': 8.06,
                                'OT DX PRCS OF RESP TRCT': 8.61,
                                'OT DX PRCS ON LUNG': 9.15,
                                'OT DX PRCS ON MUSC/SKEL': 10.49,
                                'OT DX PRCS URINARY TRCT': 8.85,
                                'OT DX PRCS; FEMALE ORGN': 6.26,
                                'OT DX RADIO & RELATED': 5.13,
                                'OT EXC CERVIX & UTERUS': 4.31,
                                'OT EXTRAOCULAR MUSC/ORB': 6.14,
                                'OT FRACTURE/DISLOC PRC': 7.06,
                                'OT INTRAOCULAR THER PRC': 6.15,
                                'OT NON-OR GI THER PRCS': 8.12,
                                'OT NON-OR LW GI THER PR': 6.79,
                                'OT NON-OR THER CARDIO': 10.44,
                                'OT NON-OR THER NERV SYS': 7.34,
                                'OT NON-OR THER PRC MUSC': 7.24,
                                'OT NON-OR THER PRC NOSE': 3.98,
                                'OT NON-OR THER PRC RESP': 10.16,
                                'OT NON-OR THER PRC SKIN': 9.94,
                                'OT NON-OR THER PRC URIN': 7.24,
                                'OT NON-OR THER PRC; FEM': 3.28,
                                'OT NON-OR THER PRCS; M': 7.52,
                                'OT NON-OR UP GI THER PR': 8.09,
                                'OT OPER FALLOPIAN TUBES': 3.34,
                                'OT OPERATIONS ON OVARY': 3.4,
                                'OT OR GI THER PRCS': 10.08,
                                'OT OR LOW GI THER PRCS': 9.67,
                                'OT OR PRCS ON VES HEAD': 9.88,
                                'OT OR PRCS VES NOT HEAD': 10.09,
                                'OT OR RX PRCS RESP SYS': 11.07,
                                'OT OR THER PRC MUSC/SKL': 7.66,
                                'OT OR THER PRC ON JOINT': 7.6,
                                'OT OR THER PRC SKN/BRST': 7.55,
                                'OT OR THER PRC; FEM ORG': 4.28,
                                'OT OR THER PRCS ON BONE': 7.51,
                                'OT OR THER PRCS URINARY': 8.66,
                                'OT OR THER PRCS; MALE': 6.48,
                                'OT OR UP GI THER PRCS': 10.12,
                                'OT ORGAN TRANSPLANTATN': 33.16,
                                'OT PHYS THER/REHAB': 12.91,
                                'OT PRCS TO ASSIST DELIV': 4.32,
                                'OT THER ENDOCRINE PRCS': 6.27,
                                'OT THER OBSTETRICAL PRC': 3.0,
                                'OT THER PRCS EYELIDS': 4.58,
                                'OT THER PRCS ON MUSCLES': 8.31,
                                'OT THER PRCS; HEM/LYMPH': 8.43,
                                'OT THERAPEUTIC EAR PRCS': 5.39,
                                'OT VASC CATH; NOT HEART': 10.4,
                                'OT VASCULAR BYP/SHUNT': 9.39,
                                'OTHER BOWEL DX PRCS': 6.86,
                                'OTHER CT SCAN': 4.5,
                                'OTHER DX NERV SYS PRCS': 11.43,
                                'OTHER DX ULTRASOUND': 5.56,
                                'OTHER GI DX PRCS': 8.11,
                                'OTHER HERNIA REPAIR': 7.66,
                                'OTHER OR HEART PRCS': 11.0,
                                'OTHER OR THER NERV SYS': 9.3,
                                'OTHER OR THER PRCS NOSE': 6.17,
                                'OTHER RADIOISOTOPE SCAN': 5.06,
                                'OTHER RESP THERAPY': 7.23,
                                'OTHER THERAPEUTIC PRCS': 6.89,
                                'PARTIAL EXCISION BONE': 10.19,
                                'PERC TRANSLUM COR ANGIO': 7.01,
                                'PERIPH VASCULAR BYPASS': 11.58,
                                'PERITONEAL DIALYSIS': 6.41,
                                'PHYS THER EXER, MANIPUL': 12.07,
                                'PLASTIC PRCS ON NOSE': 3.33,
                                'PRCS ON SPLEEN': 9.91,
                                'PRCS ON THE URETHRA': 5.56,
                                'PROCTOSCOPY & AR BIOPSY': 7.3,
                                'PROPHYLACTIC VAC/INOCUL': 5.14,
                                'PSYCHO/PSYCHI EVAL/THER': 20.75,
                                'RADIOISOTOPE BONE SCAN': 7.3,
                                'RADIOISOTOPE PULM SCAN': 4.24,
                                'RADIOISOTOPE SCAN/FUNCT': 4.35,
                                'REPAIR CUR OBS LACERATN': 3.44,
                                'REPAIR CYST-/RECT-OCELE': 2.88,
                                'REPAIR RETINAL TEAR': 3.46,
                                'RESP INTUB/MECH VENTIL': 12.32,
                                'RMVL ECTOPIC PREGNANCY': 2.92,
                                'ROUTINE CHEST X-RAY': 4.14,
                                'SKIN GRAFT': 11.41,
                                'SMALL BOWEL RESECTON': 13.38,
                                'SPINAL FUSION': 9.18,
                                'SUTURE SKIN/SUBCUT TISS': 4.88,
                                'SWAN-GANZ CATH MONITOR': 9.11,
                                'THERAPEUTIC RADIOLOGY': 11.03,
                                'THYROIDECTOMY;PART/FULL': 4.6,
                                'TONSIL-/ADENOID-ECTOMY': 3.77,
                                'TRACHE-/LARYNG-OSCOPY': 6.68,
                                'TRACHEOSTOMY; TEMP/PERM': 40.53,
                                'TRACTN, SPLNT, OT WOUND': 6.24,
                                'TRANS RES PROSTATE-TURP': 7.33,
                                'TRANSURETHRAL EXCISION': 6.79,
                                'TRTMNT,FACE FRACT/DISLC': 5.98,
                                'TRTMNT,FRAC HIP/FEMUR': 9.62,
                                'TRTMNT,FRAC LOWR EXTREM': 8.73,
                                'TRTMNT,FRAC RADIUS/ULNA': 5.94,
                                'TYMPANOPLASTY': 1.5,
                                'UNGROUPABLE': 5.53,
                                'UP GASTRO ENDOSC/BIOPSY': 7.49,
                                'UPPER GI X-RAY': 6.53,
                                'URETERAL CATHETERIZATN': 6.12,
                                'VARI VEIN STRIP;LOW LMB': 4.35}

dict_apr_drg_description = {'Abdominal pain': 4.33,
                            'Abortion w/o D&C, aspiration curettage or hysterotomy': 1.88,
                            'Acute & subacute endocarditis': 11.26,
                            'Acute anxiety & delirium states': 5.82,
                            'Acute leukemia': 19.81,
                            'Acute major eye infections': 5.35,
                            'Acute myocardial infarction': 6.5,
                            'Adjustment disorders & neuroses except depressive diagnoses': 7.9,
                            'Alcohol & drug dependence w rehab or rehab/detox therapy': 16.7,
                            'Alcohol abuse & dependence': 8.1,
                            'Alcoholic liver disease': 7.78,
                            'Allergic reactions': 3.57,
                            'Amputation of lower limb except toes': 14.74,
                            'Anal procedures': 5.59,
                            'Angina pectoris & coronary atherosclerosis': 3.91,
                            'Appendectomy': 6.16,
                            'Asthma': 4.97,
                            'BPD & oth chronic respiratory diseases arising in perinatal period': 5.25,
                            'Bacterial & tuberculous infections of nervous system': 11.32,
                            'Behavioral disorders': 11.32,
                            'Bipolar disorders': 19.22,
                            'Bone marrow transplant': 28.75,
                            'Brain contusion/laceration & complicated skull Fx, coma < 1 hr or no coma': 6.11,
                            'Breast procedures except mastectomy': 3.83,
                            'Bronchiolitis & RSV pneumonia': 5.29,
                            'Burns with skin graft except extensive 3rd degree burns': 15.09,
                            'CHEMOTHERAPY': 10.01,
                            'CVA & precerebral occlusion w infarct': 8.92,
                            'Cardiac arrest and shock': 5.11,
                            'Cardiac arrhythmia & conduction disorders': 5.58,
                            'Cardiac catheterization for coronary artery disease': 7.32,
                            'Cardiac catheterization for other non-coronary conditions': 4.47,
                            'Cardiac defibrillator & heart assist implant': 10.94,
                            'Cardiac pacemaker & defibrillator device replacement': 5.5,
                            'Cardiac pacemaker & defibrillator revision except device replacement': 6.6,
                            'Cardiac structural & valvular disorders': 5.71,
                            'Cardiac valve procedures w AMI or complex PDX': 14.73,
                            'Cardiac valve procedures w/o AMI or complex PDX': 11.79,
                            'Cardiomyopathy': 4.53,
                            'Cellulitis & other skin infections': 6.93,
                            'Cervical spinal fusion & other back/neck proc exc disc excis/decomp': 7.11,
                            'Cesarean delivery': 7.71,
                            'Chest pain': 3.21,
                            'Cholecystectomy except laparoscopic': 8.33,
                            'Chronic obstructive pulmonary disease': 7.0,
                            'Cleft lip & palate repair': 2.26,
                            'Coagulation & platelet disorders': 6.32,
                            'Cocaine abuse & dependence': 7.18,
                            'Concussion, closed skull Fx nos,uncomplicated intracranial injury, coma < 1 hr or no coma': 3.33,
                            'Connective tissue disorders': 6.91,
                            'Contusion, open wound & other trauma to skin & subcutaneous tissue': 4.13,
                            'Coronary bypass w AMI or complex PDX': 12.47,
                            'Coronary bypass w/o AMI or complex PDX': 11.11,
                            'Craniotomy except for trauma': 10.49,
                            'Craniotomy for multiple significant trauma': 14.55,
                            'Craniotomy for trauma': 11.14,
                            'Cystic fibrosis - pulmonary disease': 8.82,
                            'D&C, aspiration curettage or hysterotomy for obstetric diagnoses': 2.84,
                            'Degenerative nervous system disorders exc mult sclerosis': 11.17,
                            'Dental & oral diseases & injuries': 4.31,
                            'Depression except major depressive disorder': 9.79,
                            'Diabetes': 6.36,
                            'Digestive malignancy': 9.04,
                            'Dilation & curettage for non-obstetric diagnoses': 4.22,
                            'Disorders of gallbladder & biliary tract': 5.65,
                            'Disorders of pancreas except malignancy': 6.62,
                            'Disorders of personality & impulse control': 9.53,
                            'Diverticulitis & diverticulosis': 6.04,
                            'Dorsal & lumbar fusion proc except for curvature of back': 8.55,
                            'Dorsal & lumbar fusion proc for curvature of back': 8.16,
                            'Drug & alcohol abuse or dependence, left against medical advice': 5.87,
                            'Ear, nose, mouth, throat, cranial/facial malignancies': 11.84,
                            'Eating disorders': 13.87,
                            'Ectopic pregnancy procedure': 2.48,
                            'Electrolyte disorders except hypovolemia related': 6.4,
                            'Extensive 3rd degree burns w skin graft': 30.94,
                            'Extensive 3rd degree or full thickness burns w/o skin graft': 6.95,
                            'Extensive abdominal/thoracic procedures for mult significant trauma': 16.13,
                            'Extensive procedure unrelated to principal diagnosis': 12.68,
                            'Extracranial vascular procedures': 7.52,
                            'Eye disorders except major infections': 3.56,
                            'Eye procedures except orbit': 4.39,
                            'Facial bone procedures except major cranial/facial bone procedures': 4.74,
                            'False labor': 2.69,
                            'Female reproductive system infections': 5.09,
                            'Female reproductive system malignancy': 10.34,
                            'Female reproductive system reconstructive procedures': 2.85,
                            'Fever': 4.41,
                            'Foot & toe procedures': 9.2,
                            'Fracture of femur': 6.42,
                            'Fracture of pelvis or dislocation of hip': 6.04,
                            'Fractures & dislocations except femur, pelvis & back': 5.45,
                            'Gastrointestinal vascular insufficiency': 5.63,
                            'HIV w major HIV related condition': 7.6,
                            'HIV w multiple major HIV related conditions': 13.59,
                            'HIV w multiple significant HIV related conditions': 6.52,
                            'HIV w one signif HIV cond or w/o signif related cond': 4.32,
                            'Hand & wrist procedures': 4.76,
                            'Head trauma w coma >1 hr or hemorrhage': 7.17,
                            'Heart &/or lung transplant': 46.14,
                            'Heart failure': 8.5,
                            'Hepatic coma & other major acute liver disorders': 8.38,
                            'Hernia procedures except inguinal, femoral & umbilical': 7.11,
                            'Hip and femur fracture repair': 9.71,
                            'Hip joint replacement': 8.17,
                            'Hypertension': 3.9,
                            'Hypovolemia & related electrolyte disorders': 6.01,
                            'Inborn errors of metabolism': 5.53,
                            'Infections of upper respiratory tract': 4.23,
                            'Infectious & parasitic diseases including HIV w O.R. procedure': 17.1,
                            'Inflammatory bowel disease': 6.21,
                            'Inguinal, femoral & umbilical hernia procedures': 5.64,
                            'Interstitial & alveolar lung diseases': 7.67,
                            'Intervertebral disc excision & decompression': 6.76,
                            'Intestinal obstruction': 6.54,
                            'Intracranial hemorrhage': 8.51,
                            'Kidney & urinary tract infections': 7.4,
                            'Kidney & urinary tract malignancy': 8.14,
                            'Kidney & urinary tract procedures for malignancy': 7.38,
                            'Kidney & urinary tract procedures for nonmalignancy': 6.52,
                            'Kidney transplant': 7.81,
                            'Knee & lower leg procedures except foot': 8.02,
                            'Knee joint replacement': 6.97,
                            'Laparoscopic cholecystectomy': 6.98,
                            'Liver transplant &/or intestinal transplant': 26.74,
                            'Lymphatic & other malignancies & neoplasms of uncertain behavior': 7.98,
                            'Lymphoma, myeloma & non-acute leukemia': 10.81,
                            'Major O.R. procedures for lymphatic/hematopoietic/other neoplasms': 11.35,
                            'Major abdominal vascular procedures': 10.0,
                            'Major biliary tract procedures': 9.74,
                            'Major bladder procedures': 10.42,
                            'Major cardiothoracic repair of heart anomaly': 9.0,
                            'Major chest & respiratory trauma': 5.35,
                            'Major cranial/facial bone procedures': 8.37,
                            'Major depressive disorders & other/unspecified psychoses': 16.55,
                            'Major esophageal disorders': 5.8,
                            'Major gastrointestinal & peritoneal infections': 7.67,
                            'Major hematologic/immunologic diag exc sickle cell crisis & coagul': 8.19,
                            'Major larynx & trachea procedures': 15.53,
                            'Major male pelvic procedures': 5.68,
                            'Major pancreas, liver & shunt procedures': 10.63,
                            'Major respiratory & chest procedures': 10.2,
                            'Major respiratory infections & inflammations': 9.76,
                            'Major skin disorders': 7.14,
                            'Major small & large bowel procedures': 11.51,
                            'Major stomach, esophageal & duodenal procedures': 10.82,
                            'Male reproductive system diagnoses except malignancy': 5.29,
                            'Malfunction, reaction & complication of GI device or procedure': 6.81,
                            'Malfunction, reaction, complic of genitourinary device or proc': 8.03,
                            'Malfunction, reaction, complic of orthopedic device or procedure': 6.81,
                            'Malfunction,reaction,complication of cardiac/vasc device or procedure': 6.8,
                            'Malignancy of hepatobiliary system & pancreas': 7.78,
                            'Malignancy, male reproductive system': 12.37,
                            'Malignant breast disorders': 11.12,
                            'Malnutrition, failure to thrive & other nutritional disorders': 8.89,
                            'Mastectomy procedures': 3.66,
                            'Menstrual & other female reproductive system disorders': 3.08,
                            'Mental illness diagnosis w O.R. procedure': 19.97,
                            'Migraine & other headaches': 3.75,
                            'Moderately extensive procedure unrelated to principal diagnosis': 11.02,
                            'Multiple sclerosis & other demyelinating diseases': 7.22,
                            'Multiple significant trauma w/o O.R. procedure': 7.34,
                            'Musculoskeletal & other procedures for multiple significant trauma': 12.88,
                            'Musculoskeletal malignancy & pathol fracture d/t muscskel malig': 9.82,
                            'Nephritis & nephrosis': 7.11,
                            'Nervous system malignancy': 9.1,
                            'Non-bacterial infections of nervous system exc viral meningitis': 9.65,
                            'Nonextensive procedure unrelated to principal diagnosis': 9.2,
                            'Nonspecific CVA & precerebral occlusion w/o infarct': 4.14,
                            'Nontraumatic stupor & coma': 7.88,
                            'O.R. procedure for other complications of treatment': 7.7,
                            'OTHER VASCULAR PROCEDURES': 9.48,
                            'Opioid abuse & dependence': 7.17,
                            'Orbital procedures': 4.54,
                            'Organic mental health disturbances': 15.43,
                            'Osteomyelitis, septic arthritis & other musculoskeletal infections': 9.2,
                            'Other & unspecified gastrointestinal hemorrhage': 6.41,
                            'Other O.R. proc for obstetric diagnoses except delivery diagnoses': 4.02,
                            'Other O.R. procedures for lymphatic/hematopoietic/other neoplasms': 11.85,
                            'Other aftercare & convalescence': 11.75,
                            'Other anemia & disorders of blood & blood-forming organs': 5.33,
                            'Other antepartum diagnoses': 5.36,
                            'Other back & neck disorders, fractures & injuries': 6.22,
                            'Other bladder procedures': 7.18,
                            'Other cardiothoracic & thoracic vascular procedures': 9.61,
                            'Other circulatory system diagnoses': 4.92,
                            'Other circulatory system procedures': 11.74,
                            'Other complications of treatment': 5.23,
                            'Other digestive system & abdominal procedures': 8.36,
                            'Other digestive system diagnoses': 5.12,
                            'Other disorders of nervous system': 8.11,
                            'Other disorders of the liver': 6.05,
                            'Other drug abuse & dependence': 8.27,
                            'Other ear, nose, mouth & throat procedures': 4.96,
                            'Other ear, nose, mouth,throat & cranial/facial diagnoses': 3.93,
                            'Other endocrine disorders': 6.4,
                            'Other esophageal disorders': 4.56,
                            'Other female reproductive system & related procedures': 4.7,
                            'Other gastroenteritis, nausa & vomiting': 4.56,
                            'Other hepatobiliary, pancreas & abdominal procedures': 9.49,
                            'Other infectious & parasitic diseases': 6.69,
                            'Other injury, poisoning & toxic effect diagnoses': 7.09,
                            'Other kidney & urinary tract diagnoses, signs & symptoms': 5.17,
                            'Other kidney, urinary tract & related procedures': 11.11,
                            'Other major head & neck procedures': 6.45,
                            'Other male reproductive system & related procedures': 5.86,
                            'Other mental health disorders': 10.75,
                            'Other musculoskeletal system & connective tissue diagnoses': 5.47,
                            'Other musculoskeletal system & connective tissue procedures': 6.93,
                            'Other nervous system & related procedures': 7.47,
                            'Other pneumonia': 7.56,
                            'Other procedures for endocrine, nutritional & metabolic disorders': 12.74,
                            'Other procedures of blood & blood-forming organs': 6.52,
                            'Other respiratory & chest procedures': 8.26,
                            'Other respiratory diagnoses except signs, symptoms & minor diagnoses': 5.62,
                            'Other significant hip and femur surgery': 7.85,
                            'Other skin, subcutaneous tissue & breast disorders': 4.75,
                            'Other skin, subcutaneous tissue & related procedures': 6.87,
                            'Other small & large bowel procedures': 7.98,
                            'Other stomach, esophageal & duodenal procedures': 7.27,
                            'Pancreas transplant': 18.91,
                            'Partial thickness burns without skin graft': 6.11,
                            'Pelvic evisceration, radical hysterectomy & other radical GYN procs': 5.56,
                            'Penis procedures': 4.69,
                            'Peptic ulcer & gastritis': 5.42,
                            'Percutaneous coronary intervention w AMI': 6.84,
                            'Percutaneous coronary intervention w/o AMI': 6.53,
                            'Peripheral & other vascular disorders': 6.3,
                            'Peripheral, cranial & autonomic nerve disorders': 5.64,
                            'Peritoneal adhesiolysis': 9.77,
                            'Perm cardiac pacemaker implant w/o AMI, heart failure or shock': 6.86,
                            'Permanent cardiac pacemaker implant w AMI, heart failure or shock': 9.8,
                            'Pituitary & adrenal procedures': 6.01,
                            'Poisoning of medicinal agents': 5.04,
                            'Post-op, post-trauma, other device infections w O.R. procedure': 10.9,
                            'Post-operative, post-traumatic, other device infections': 8.1,
                            'Postpartum & post abortion diagnoses w/o procedure': 3.77,
                            'Preterm labor': 4.82,
                            'Procedure w diag of rehab, aftercare or oth contact w health service': 8.16,
                            'Procedures for obesity': 4.0,
                            'Pulmonary embolism': 6.65,
                            'RENAL FAILURE': 8.92,
                            'Radiotherapy': 9.46,
                            'Rehabilitation': 16.46,
                            'Renal dialysis access device procedure only': 12.16,
                            'Respiratory Failure': 8.63,
                            'Respiratory malignancy': 9.09,
                            'Respiratory signs, symptoms & minor diagnoses': 3.95,
                            'Respiratory system diagnosis w ventilator support 96+ hours': 20.52,
                            'Schizophrenia': 30.05,
                            'Seizure': 6.2,
                            'Septicemia & disseminated infections': 11.45,
                            'Shoulder, upper arm & forearm procedures except joint replacement': 5.3,
                            'Sickle cell anemia crisis': 9.23,
                            'Signs, symptoms & other factors influencing health status': 6.14,
                            'Sinus & mastoid procedures': 4.04,
                            'Skin graft for skin & subcutaneous tissue diagnoses': 8.01,
                            'Skin graft, except hand, for musculoskeletal & connective tissue diagnoses': 11.77,
                            'Skin ulcers': 8.86,
                            'Spinal disorders & injuries': 10.61,
                            'Spinal procedures': 7.94,
                            'Splenectomy': 8.3,
                            'Syncope & collapse': 4.58,
                            'Tendon, muscle & other soft tissue procedures': 7.36,
                            'Testes & scrotal procedures': 6.37,
                            'Thyroid, parathyroid & thyroglossal procedures': 4.28,
                            'Tonsil & adenoid procedures': 3.72,
                            'Toxic effects of non-medicinal substances': 4.52,
                            'Tracheostomy w MV 96+ hours w extensive procedure or ECMO': 46.0,
                            'Tracheostomy w MV 96+ hours w/o extensive procedure': 41.83,
                            'Transient ischemia': 4.14,
                            'Transurethral prostatectomy': 6.21,
                            'Urethral & transurethral procedures': 5.76,
                            'Urinary stones & acquired upper urinary tract obstruction': 3.65,
                            'Uterine & adnexa procedures for leiomyoma': 5.33,
                            'Uterine & adnexa procedures for non-malignancy except leiomyoma': 3.6,
                            'Uterine & adnexa procedures for non-ovarian & non-adnexal malig': 6.45,
                            'Uterine & adnexa procedures for ovarian & adnexal malignancy': 7.23,
                            'Vaginal delivery': 3.45,
                            'Vaginal delivery w complicating procedures exc sterilization &/or D&C': 2.78,
                            'Vaginal delivery w sterilization &/or D&C': 2.96,
                            'Ventricular shunt procedures': 8.38,
                            'Vertigo & other labyrinth disorders': 3.71,
                            'Viral illness': 5.06,
                            'Viral meningitis': 5.85}
                
dict_apr_mdc_description = {'Alcohol/Drug Use and Alcohol/Drug Induced Organic Mental Disorders': 9.06,
                        'Burns': 10.81,
                        'Diseases and Disorders of Blood, Blood Forming Organs and Immunological Disorders': 7.22,
                        'Diseases and Disorders of the Circulatory System': 7.71,
                        'Diseases and Disorders of the Digestive System': 7.33,
                        'Diseases and Disorders of the Eye': 4.16,
                        'Diseases and Disorders of the Female Reproductive System': 5.46,
                        'Diseases and Disorders of the Hepatobiliary System and Pancreas': 7.89,
                        'Diseases and Disorders of the Kidney and Urinary Tract': 7.81,
                        'Diseases and Disorders of the Male Reproductive System': 6.65,
                        'Diseases and Disorders of the Musculoskeletal System and Conn Tissue': 7.64,
                        'Diseases and Disorders of the Nervous System': 8.61,
                        'Diseases and Disorders of the Respiratory System': 8.57,
                        'Diseases and Disorders of the Skin, Subcutaneous Tissue and Breast': 6.78,
                        'Ear, Nose, Mouth, Throat and Craniofacial Diseases and Disorders': 5.34,
                        'Endocrine, Nutritional and Metabolic Diseases and Disorders': 6.78,
                        'Human Immunodeficiency Virus Infections': 9.27,
                        'Infectious and Parasitic Diseases, Systemic or Unspecified Sites': 12.42,
                        'Lymphatic, Hematopoietic, Other Malignancies, Chemotherapy and Radiotherapy': 12.99,
                        'Mental Diseases and Disorders': 18.55,
                        'Multiple Significant Trauma': 11.24,
                        'Poisonings, Toxic Effects, Other Injuries and Other Complications of Treatment': 5.84,
                        'Pregnancy, Childbirth and the Puerperium': 4.62,
                        'Rehabilitation, Aftercare, Other Factors Influencing Health Status and Other Health Service Contacts': 12.1}

dict_type_of_admission = {'Elective': 8.22,
                        'Emergency': 8.63,
                        'Newborn': 5.06,
                        'Not Available': 5.8,
                        'Trauma': 7.13,
                        'Urgent': 8.68}
                
dict_apr_severity_of_illness_description = {'Minor': 1, 'Moderate': 2, 'Major': 3, 'Extreme': 4} 
                
dict_apr_risk_of_mortality = {'Minor': 1, 'Moderate': 2, 'Major': 3, 'Extreme': 4} 
                
dict_gender = {'F': 0, 'M': 1} 

dict_apr_medical_surgical_description_list = {'Medical': 0, 'Surgical': 1} 
                
dict_emergency_department_indicator_list = {'Y': 1, 'N': 0}
